### ISSUE TITLE
can't see the examples notebooks in http://127.0.0.1:8000/

### ISSUE THREAD

**Issue by julian-passebecq** [mljar/mercury-examples#1]
EDIT :  it is now working , i did a clean install of my anaconda environment with **conda** install instead of **pip**

<img width="936" alt="image" src="https://user-images.githubusercontent.com/64646018/218969170-422d3f03-e084-4a21-a1b5-39fa72169982.png">

Hi,

I downloaded the examples notebook, when going to the directory and launching mercury on terminal, i have this error, and i can't see the notebook in `http://127.0.0.1:8000/`

`Your notebook kernel name is set to 'mex'.
In this system available kernels are [].
Sorry, cant automatically update the kernel name in the notebook.
Successfully added a notebook (id:None)`

**Comment by pplonski** [comment]
Great, I've added Mercury to conda-forge yesterday. Will update docs.
