### ISSUE TITLE
please add requirements.txt in Data_analist _job

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury-examples#2]
1. Please add a `requirements.txt` file with the required packages to run the notebook in `use-cases/Data_analist_job`.

2. Maybe change the directory and file names to `-` instead `_` to be consistent with other files in the repo. 

3. Last thing, please stick to `analyst` instead `analist` - the first article from google search https://thecontentauthority.com/blog/analyst-vs-analist

**Comment by adrianblazeusz** [comment]
All done!
