### ISSUE TITLE
dashboard for data analyst job listings

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury-examples#3]
- [x] images are [blurred](https://raw.githubusercontent.com/mljar/mercury-examples/main/use-cases/data-analyst-job/images/import.jpg), please try to increase the font (or zoom entire notebook) and do screenshot in PNG 
- [x] not reading data from the data source provided in the repo, you have `df = pd.read_csv("gsearch_jobs.csv")`
- [x] description about data should be improved (full sentences + more info)
- [x] last plot has a different size than rest
- [x] please add information message for cases when user will deselect all values from multi select widget and final data frame will be empty

**Comment by pplonski** [comment]
1. can we improve in this chart? maybe add two bars? one for remote and one for not-remote
![image](https://user-images.githubusercontent.com/6959032/233565191-99f96d44-39d6-4431-a153-b8510cf68178.png)


2. `What are the working hours for Junior, Mid, Senior` please change to `Contract type`

3. can we add more skills in widget before the last plot?
4. can we have computed variables in the markdown code?
5. typos in chart titles `finde`
6. `df = pd.read_csv("df-job.al.zip")` should work - no need to unzip
7. can we add information about when was the first listing, and when was last listing? can we do a plot with number of listings in time? 
8. can we add word cloud plot with skills?
9. do we have information about location? all listings are from US? can we do a plot with map showing number of listings per country? or per state?

**Comment by adrianblazeusz** [comment]
1. Done
2. Done
3. Done, I increased the number to 20
4. Done
5. Done, thank you and sorry!
6. Done
7. The data is from the "last" 24 hours
8. Done
9. Most job listings do not include where they need an employee, instead they write if they are needed in the USA or write "Anywhere". I tried to make a meaningful map of the US states, but it didn't work out. 
10. I changed the way of counting "avg sallary yearly by skill.

**Comment by adrianblazeusz** [comment]
10. I changed the way of counting "avg sallary yearly by skill.

**Comment by pplonski** [comment]
- [x] add description about dataset
- [x] link to code repository
- [x] describe data cleaning step
- [x] describe code for plotting part
- [x] make article as your story, try to explain steps needed to build such dashboard for newbie


title: Create dashboard for 15,963 Data Analyst job listings in Python

**Comment by pplonski** [comment]
In the notebook there are many places with code

```
plt.title(mr.Markdown(
```

It is wrong. It should be only

```
mr.Markdown(
```


Do you know why?

**Comment by adrianblazeusz** [comment]
I think I understand this now. 
If I try to pass Markdown text through the plt.title() function, it will be formatted as a string, because plt.title() only takes that format as an argument.
Thank you for the clue.

**Comment by adrianblazeusz** [comment]
I corrected the typo, could you upload the article please.
